stages:
    - build

build:
    image: reactnativecommunity/react-native-android
    stage: build
    script:
        - echo "Androied Studio setup"
        - sudo su 
        - sudo apt install openjdk-11-jdk -y 
        - sudo add-apt-repository ppa:maarten-fonville/android-studio
        - sudo apt update -y
        - sudo apt install android-studio -y
        - sudo apt-get install android-sdk -y
        - export ANDROID_HOME=/usr/lib/android-sdk
        - wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        - unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools
        - sudo mv cmdline-tools $ANDROID_HOME/
        - export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH
        - yes | sdkmanager --licenses
        - echo "Start building App"
        -  chmod +x gradlew
        - ./gradlew clean
        - ./gradlew build
        - echo "Application successfully deployed...."
    artifacts:
        paths:
            - app/build/
    only:
        - test