image: jangrewe/gitlab-ci-android

stages:
- build
- test
- release
- deploy
- send_email

assembleRelease:
  stage: release
  script:
  - echo "Start Release App"
  - chmod +x gradlew
  - ./gradlew assembleRelease
  artifacts:
    name: "COVIDReport.apk"
    paths:
    - app/build/outputs/apk/release
    expire_in: 1 week

deployRelease:
  stage: deploy
  script:
    #--release.dir=app/build/outputs/apk/release
    --app.name=BestAppEver
    --dropbox.token=$DROPBOX_TOKEN
    --dropbox.folder=release
    --changelog.file=CHANGELOG
    --template.file=TEMPLATE
    --zapier.hook=$ZAPIER_EMAIL_HOOK
    --email.to=$EMAIL_TARGET
      
