image: jangrewe/gitlab-ci-android

stages:
- build
- test
- release
- empaquetar
- deploy
- send_email

assembleRelease:
  stage: release
  script:
  - echo "Start Release App"
  - chmod +x gradlew
  - ./gradlew assembleRelease
  
  
empaquetar:
  script:
    - zip -r content.zip app
  artifacts:
    paths:
      - app/build/outputs/apk/content.zip

      
