image: jangrewe/gitlab-ci-android

stages:
- build
- test
- release
- deploy
- send_email

assembleRelease:
  stage: release
  script:
  - echo "Start Release App"
  - chmod +x gradlew
  - ./gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/apk/release
    expire_in: 1 week

send_email:
  stage: send_email
  script: curl -s --user "api:$MAILGUN_API_KEY" 
      "https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages"
      -F from='Gitlab <gitlab@example.com>'
      -F to=$GITLAB_USER_EMAIL
      -F subject='Test results + report'
      -F text='Testing some Mailgun awesomeness!'
      -F attachment='@app/build/outputs/apk/release/app-release-unsigned.apk'
