image: jangrewe/gitlab-ci-android

stages:
- build
- test
- release
- empaquetar
- deploy
- send_email

assembleRelease:
  stage: release
  script:
  - echo "Start Release App"
  - chmod +x gradlew
  - ./gradlew assembleRelease
  artifacts:
    name: "COVIDReport.apk"
    paths:
    - app/build/
    expire_in: 1 week
  
deploy:
  stage: deploy
  script:
    - zip -r /zip/content.zip app

      
