image: jangrewe/gitlab-ci-android
stages:
  - build
  - updraft

buildProd:
  stage: build

  script:
    - chmod +x gradlew
    - ./gradlew app:assembleProdRelease

  artifacts:
    paths:
      - app/build/outputs/apk/prod/release/*.apk

 

deploy:
  stage: updraft

  script:
  - |
    curl \
      -F whats_new="Gitlab build" \
      -F "app=@app/build/outputs/apk/ prod/release/android.apk" \
      -X PUT https://getupdraft.com/api/ app_upload/$UPDRAFT_APP_KEY /$UPDRAFT_API_KEY/