stages:
    - build

build:
    image: reactnativecommunity/react-native-android
    stage: build
    script:
        - echo "Start building App"
        -  chmod +x gradlew
        - ./gradlew clean
        - ./gradlew build
        - echo "Application successfully deployed...."
    artifacts:
        paths:
            - app/build/
    only:
        - master