stages:
    - build

build:
    image: reactnativecommunity/react-native-android
    stage: build
    script:
        #- yarn install
        #-  chmod +x gradlew
        #- ./gradlew assembleMyBuild --stacktrace
        #- gradle build
        - ./gradlew clean
        - ./gradlew build
    artifacts:
        paths:
            - app/build/
