image: jangrewe/gitlab-ci-android

stages:
- build
- test
- release
- empaquetar
- deploy
- send_email

assembleRelease:
  stage: release
  script:
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
    - |
      curl \
        -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" \
        -F channels="${SLACK_CHANNEL_ID}" \
        -F initial_comment="Hello team! Here is the latest APK" \
        -F "file=@$(find app/build/outputs/apk/debug -name 'MyApp*')" \
        https://slack.com/api/files.upload
  artifacts:
    paths:
      - app/build/outputs/apk/debug