image: jangrewe/gitlab-ci-android

stages:
- build
- test
- release
- empaquetar
- deploy
- send_email

assembleRelease:
  stage: release
  script:
  - echo "Start Release App"
  - chmod +x gradlew
  - ./gradlew assembleRelease
  artifacts:
    name: "COVIDReport.apk"
    paths:
    - zip/build
    - zip -r zip/content.zip app
    expire_in: 1 week
  

send_email:
  stage: send_email
  script: curl -s --user "api:$MAILGUN_API_KEY" 
      "https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages"
      -F from='Gitlab <gitlab@example.com>'
      -F to=$GITLAB_USER_EMAIL
      -F subject='Test results + report'
      -F text='Testing some Mailgun awesomeness!'
      -F attachment='@zip/content.zip'

      
