image: i1

stages:
  - test
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
testDebug:
  tags:
  - "v2"
  stage: test
  before_script:
    - chmod +x ./gradlew
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew test
  